# iTHOR + Target Houses Target Objects
- AlarmClock
- Apple
- BaseballBat
- BasketBall
- Bed
- Book
- Bowl
- Box
- Bread
- CoffeeMachine
- Cup
- DiningTable
- FloorLamp
- Fridge
- GarbageCan
- HousePlant
- Laptop
- Lettuce
- Microwave
- Mug
- Pan
- Pot
- Potato
- SoapBottle
- Sofa
- SprayBottle
- Television
- Toaster
- Toilet
- Tomato
- Vase
