# RoboTHOR + Habitat 2021 Challenge Target Objects
- AlarmClock
- Apple
- BaseballBat
- BasketBall
- Bed
- Bowl
- Chair
- CounterTop
- DiningTable
- Dresser
- GarbageCan
- HousePlant
- Laptop
- Mug
- Sink
- Sofa
- SprayBottle
- Stool
- Television
- Toilet
- Vase
