# RoboTHOR + Habitat 2022 Challenge Target Objects
- AlarmClock
- Apple
- BaseballBat
- BasketBall
- Bed
- Bowl
- Chair
- GarbageCan
- HousePlant
- Laptop
- Mug
- Sofa
- SprayBottle
- Television
- Toilet
- Vase
